PartII_Week04\HW(包欣平)
phoebe4561/taipei-day-trip-website pull request #5
Opened 2021-05-13 13:29 UTC by phoebe4561

老師好:
[上線網址] http://18.178.201.21:3000/

2021-05-13 16:25 UTC, cwpeng requested changes
我用相同的 Email 重複註冊兩次，都會成功哦，請處理這個問題 ~

2021-05-14 07:14 UTC, phoebe4561 commented
> 我用相同的 Email 重複註冊兩次，都會成功哦，請處理這個問題 ~

已修正問題!
[上線網址] http://18.178.201.21:3000/

2021-05-14 07:17 UTC, cwpeng commented
看起來是 OK 了，但請發一個 Review Request 給我哦 ~

2021-05-14 08:03 UTC, cwpeng approved these changes
OK.

2021-05-14 09:22 UTC, merged